services:
  - type: web
    name: stratify-app
    runtime: python
    plan: starter
    rootDir: aphde
    buildCommand: pip install -U pip && pip install -e .
    startCommand: streamlit run app/main.py --server.address 0.0.0.0 --server.port $PORT --server.headless true
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: "false"
      - key: STREAMLIT_SERVER_ENABLE_CORS
        value: "true"
      - key: STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION
        value: "true"
