services:
  - type: web
    name: stratify
    runtime: python
    buildCommand: pip install -e .
    startCommand: PYTHONPATH=/opt/render/project/src streamlit run aphde/app/main.py --server.address 0.0.0.0 --server.port $PORT
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src
